"""empty message

Revision ID: 635dc6b6ec73
Revises: b03e205cc3aa
Create Date: 2022-08-13 05:26:40.749785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635dc6b6ec73'
down_revision = 'b03e205cc3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
